"""initial_schema

Revision ID: d590d64b2fc2
Revises: 
Create Date: 2025-11-19 16:38:28.151179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd590d64b2fc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_server_configs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('command', sa.String(), nullable=True),
    sa.Column('args', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('env', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('auth_type', sa.String(), nullable=False),
    sa.Column('auth_secret_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retry_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auto_reconnect', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('model_configs',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('api_key_secret_id', sa.String(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('guardrails', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_suggestions',
    sa.Column('category', sa.String(), nullable=False, comment='Category: question, theme, angle, community-sample'),
    sa.Column('text', sa.Text(), nullable=False, comment='Prompt suggestion text'),
    sa.Column('icon', sa.String(), nullable=True, comment='Icon identifier or emoji'),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False, comment='Tags for filtering suggestions'),
    sa.Column('locale', sa.String(), nullable=False, comment='Language code (en, zh, etc.)'),
    sa.Column('required_skills', postgresql.ARRAY(sa.String()), nullable=False, comment='Required skill package names'),
    sa.Column('usage_count', sa.String(), nullable=False, comment='Number of times this suggestion was used'),
    sa.Column('rating', sa.String(), nullable=True, comment='Average user rating (0-5)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_suggestions_category'), 'prompt_suggestions', ['category'], unique=False)
    op.create_index(op.f('ix_prompt_suggestions_locale'), 'prompt_suggestions', ['locale'], unique=False)
    op.create_table('skill_packages',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('manifest_path', sa.String(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('default_enabled', sa.Boolean(), nullable=False),
    sa.Column('required_resources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exposed_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sandbox_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('subscription_plan', sa.String(), nullable=False),
    sa.Column('ai_chats_left', sa.Integer(), nullable=False),
    sa.Column('ai_chats_total', sa.Integer(), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('subscription_histories',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
    sa.Column('previous_plan', sa.String(), nullable=True, comment='Previous subscription plan'),
    sa.Column('new_plan', sa.String(), nullable=False, comment='New subscription plan: free, pro'),
    sa.Column('change_type', sa.String(), nullable=False, comment='Change type: upgrade, downgrade, renewal, cancellation, expiration'),
    sa.Column('amount_paid', sa.String(), nullable=True, comment='Amount paid (stored as string to avoid floating point issues)'),
    sa.Column('currency', sa.String(), nullable=False, comment='Currency code'),
    sa.Column('payment_method', sa.String(), nullable=True, comment='Payment method used'),
    sa.Column('transaction_id', sa.String(), nullable=True, comment='External payment transaction ID'),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False, comment='Subscription start date'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Subscription expiration date'),
    sa.Column('previous_ai_chats_total', sa.Integer(), nullable=True, comment='Previous AI chat quota'),
    sa.Column('new_ai_chats_total', sa.Integer(), nullable=False, comment='New AI chat quota'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes about this change'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional metadata'),
    sa.Column('status', sa.String(), nullable=False, comment='Status: active, cancelled, expired, pending'),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True, comment='Cancellation date'),
    sa.Column('cancellation_reason', sa.Text(), nullable=True, comment='Reason for cancellation'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_histories_change_type'), 'subscription_histories', ['change_type'], unique=False)
    op.create_index(op.f('ix_subscription_histories_transaction_id'), 'subscription_histories', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_subscription_histories_user_id'), 'subscription_histories', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_project_id', sa.UUID(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writing_styles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('formality_level', sa.Integer(), nullable=False),
    sa.Column('vocabulary_complexity', sa.Integer(), nullable=False),
    sa.Column('sample_texts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('style_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True, comment='User ID who performed the action'),
    sa.Column('workspace_id', sa.UUID(), nullable=True, comment='Workspace ID if action was workspace-scoped'),
    sa.Column('entity_type', sa.String(), nullable=False, comment='Type of entity: page, file, model, skill, workspace, user, etc.'),
    sa.Column('entity_id', sa.String(), nullable=False, comment='ID of the entity being acted upon'),
    sa.Column('action', sa.String(), nullable=False, comment='Action: create, update, delete, import, export, activate, deactivate'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Detailed action payload'),
    sa.Column('ip_address', sa.String(), nullable=True, comment='IP address of the request'),
    sa.Column('user_agent', sa.String(), nullable=True, comment='User agent string'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional metadata'),
    sa.Column('status', sa.String(), nullable=False, comment='Status: success, failed, partial'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if action failed'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('active_model_id', sa.String(), nullable=False),
    sa.Column('active_skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('message_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_workspace_id'), 'chat_sessions', ['workspace_id'], unique=False)
    op.create_table('context_files',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('related_pages', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_files_workspace_id'), 'context_files', ['workspace_id'], unique=False)
    op.create_table('inspiration_boards',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False, comment='Inspiration board title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Board description'),
    sa.Column('related_page_ids', postgresql.ARRAY(sa.UUID()), nullable=False, comment='IDs of related pages'),
    sa.Column('suggestions', postgresql.ARRAY(sa.UUID()), nullable=False, comment='IDs of included prompt suggestions'),
    sa.Column('community_sample_ids', postgresql.ARRAY(sa.String()), nullable=False, comment='IDs of community examples'),
    sa.Column('notes', sa.Text(), nullable=True, comment="User's custom notes for this board"),
    sa.Column('status', sa.String(), nullable=False, comment='Board status: active, archived'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspiration_boards_workspace_id'), 'inspiration_boards', ['workspace_id'], unique=False)
    op.create_table('memories',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_id', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_workspace_id'), 'memories', ['workspace_id'], unique=False)
    op.create_table('pages',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('tiptap_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('linked_plan_id', sa.UUID(), nullable=True),
    sa.Column('linked_files', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('linked_memories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('outline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_edited_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_edited_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_slug'), 'pages', ['slug'], unique=False)
    op.create_index(op.f('ix_pages_workspace_id'), 'pages', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('writing_plans',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('source_prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_task_id', sa.UUID(), nullable=True),
    sa.Column('task_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writing_plans_workspace_id'), 'writing_plans', ['workspace_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('session_id', sa.UUID(), nullable=False, comment='Chat session ID'),
    sa.Column('plan_id', sa.UUID(), nullable=True, comment='Writing plan ID if associated'),
    sa.Column('trigger', sa.String(), nullable=False, comment='Trigger type: user_request, scheduled, system'),
    sa.Column('status', sa.String(), nullable=False, comment='Status: pending, running, paused, completed, failed'),
    sa.Column('current_step_id', sa.UUID(), nullable=True, comment='Current step ID being executed'),
    sa.Column('related_sub_agents', postgresql.ARRAY(sa.UUID()), nullable=False, comment='IDs of related sub-agent contexts'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if execution failed'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional execution metadata'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='Execution start time'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Execution completion time'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['writing_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_plan_id'), 'agent_runs', ['plan_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_session_id'), 'agent_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_trigger'), 'agent_runs', ['trigger'], unique=False)
    op.create_table('chat_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('streaming_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('referenced_files', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('referenced_memories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('file_versions',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_path', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['context_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_versions_file_id'), 'file_versions', ['file_id'], unique=False)
    op.create_table('todo_tasks',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('step_type', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('dependencies', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assigned_agent_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['writing_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_tasks_plan_id'), 'todo_tasks', ['plan_id'], unique=False)
    op.create_table('upload_assets',
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='Workspace ID'),
    sa.Column('uploader_id', sa.UUID(), nullable=True, comment='User who uploaded the file'),
    sa.Column('file_id', sa.UUID(), nullable=False, comment='Reference to ContextFile'),
    sa.Column('original_name', sa.String(), nullable=False, comment='Original filename'),
    sa.Column('file_type', sa.String(), nullable=False, comment='File type: document, image, audio, video, spreadsheet, presentation'),
    sa.Column('status', sa.String(), nullable=False, comment='Processing status: processing, ready, failed'),
    sa.Column('processing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Processing metadata including extracted text, thumbnails, OCR status'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if processing failed'),
    sa.Column('mime_type', sa.String(), nullable=True, comment='MIME type of the file'),
    sa.Column('file_size', sa.String(), nullable=True, comment='File size in bytes'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['context_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_assets_file_id'), 'upload_assets', ['file_id'], unique=False)
    op.create_index(op.f('ix_upload_assets_file_type'), 'upload_assets', ['file_type'], unique=False)
    op.create_index(op.f('ix_upload_assets_status'), 'upload_assets', ['status'], unique=False)
    op.create_index(op.f('ix_upload_assets_uploader_id'), 'upload_assets', ['uploader_id'], unique=False)
    op.create_index(op.f('ix_upload_assets_workspace_id'), 'upload_assets', ['workspace_id'], unique=False)
    op.create_table('agent_steps',
    sa.Column('run_id', sa.UUID(), nullable=False, comment='Agent run ID'),
    sa.Column('step_type', sa.String(), nullable=False, comment='Step type: plan, tool, file_op, skill_activation, mcp_call'),
    sa.Column('name', sa.String(), nullable=True, comment='Step name or description'),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Input data for this step'),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Output data from this step'),
    sa.Column('status', sa.String(), nullable=False, comment='Status: pending, running, completed, failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if step failed'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='Step start time'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='Step completion time'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional step metadata'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_steps_run_id'), 'agent_steps', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_steps_step_type'), 'agent_steps', ['step_type'], unique=False)
    op.create_table('sub_agent_contexts',
    sa.Column('parent_run_id', sa.UUID(), nullable=False, comment='Parent agent run ID'),
    sa.Column('agent_type', sa.String(), nullable=False, comment='Agent type: research, translation, editing, fact_check'),
    sa.Column('scoped_files', postgresql.ARRAY(sa.UUID()), nullable=False, comment='File IDs accessible to this sub-agent'),
    sa.Column('scoped_memories', postgresql.ARRAY(sa.UUID()), nullable=False, comment='Memory IDs accessible to this sub-agent'),
    sa.Column('temp_directory', sa.String(), nullable=True, comment='Temporary directory path for this sub-agent'),
    sa.Column('instructions', sa.Text(), nullable=False, comment='Instructions for the sub-agent'),
    sa.Column('result_file_id', sa.UUID(), nullable=True, comment='Result file ID produced by this sub-agent'),
    sa.Column('status', sa.String(), nullable=False, comment='Status: pending, running, completed, failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if sub-agent execution failed'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Completion time'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional sub-agent metadata'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_agent_contexts_agent_type'), 'sub_agent_contexts', ['agent_type'], unique=False)
    op.create_index(op.f('ix_sub_agent_contexts_parent_run_id'), 'sub_agent_contexts', ['parent_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_agent_contexts_parent_run_id'), table_name='sub_agent_contexts')
    op.drop_index(op.f('ix_sub_agent_contexts_agent_type'), table_name='sub_agent_contexts')
    op.drop_table('sub_agent_contexts')
    op.drop_index(op.f('ix_agent_steps_step_type'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_run_id'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_upload_assets_workspace_id'), table_name='upload_assets')
    op.drop_index(op.f('ix_upload_assets_uploader_id'), table_name='upload_assets')
    op.drop_index(op.f('ix_upload_assets_status'), table_name='upload_assets')
    op.drop_index(op.f('ix_upload_assets_file_type'), table_name='upload_assets')
    op.drop_index(op.f('ix_upload_assets_file_id'), table_name='upload_assets')
    op.drop_table('upload_assets')
    op.drop_index(op.f('ix_todo_tasks_plan_id'), table_name='todo_tasks')
    op.drop_table('todo_tasks')
    op.drop_index(op.f('ix_file_versions_file_id'), table_name='file_versions')
    op.drop_table('file_versions')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_agent_runs_trigger'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_session_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_plan_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_writing_plans_workspace_id'), table_name='writing_plans')
    op.drop_table('writing_plans')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_pages_workspace_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_slug'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_memories_workspace_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_inspiration_boards_workspace_id'), table_name='inspiration_boards')
    op.drop_table('inspiration_boards')
    op.drop_index(op.f('ix_context_files_workspace_id'), table_name='context_files')
    op.drop_table('context_files')
    op.drop_index(op.f('ix_chat_sessions_workspace_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('writing_styles')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_subscription_histories_user_id'), table_name='subscription_histories')
    op.drop_index(op.f('ix_subscription_histories_transaction_id'), table_name='subscription_histories')
    op.drop_index(op.f('ix_subscription_histories_change_type'), table_name='subscription_histories')
    op.drop_table('subscription_histories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('skill_packages')
    op.drop_index(op.f('ix_prompt_suggestions_locale'), table_name='prompt_suggestions')
    op.drop_index(op.f('ix_prompt_suggestions_category'), table_name='prompt_suggestions')
    op.drop_table('prompt_suggestions')
    op.drop_table('model_configs')
    op.drop_table('mcp_server_configs')
    # ### end Alembic commands ###
